env:
    env_name: &env_name "BipedalWalker-v3"
    record: True
    seed: 69420
    min_expected_reward: 300
    ## NEED TO PUT STATE INFO HERE
    discrete: False
    obs_dim: 24
    action_dim: 4

network:
    network_type: "normal"
    network_config:
        normal:
        cnn:
        lstm: 

model_training:
    num_episodes_eval: 5
    record_freq: 5
    summary_freq: 1
    use_baseline: &use_baseline True
    normalize_advantage: True  
    device: "gpu" # cpu/gpu
    compile: False
    compile_mode: "default"

hyper_params: 
    max_ep_len: 1600 # maximum episode length (Note: this value must be strictly less than or equal to our batch size)
    num_batches: 50000 # number of batches trained on
    batch_size: 1600 # number of steps used to compute each policy update
    learning_rate: 0.0001
    gamma: 0.98 # the discount factor
    n_layers: 2
    layer_size: 256

output:
    output_path: &output_path !join ["ModelWeights/", *env_name, "-{}-"]
    actor_output: !join [*output_path, "/actor.weights.pt"]
    critic_output: !join [*output_path, "/critic.weights.pt"]
    log_path: !join [*output_path, "/log.txt"]
    scores_output: !join [*output_path, "/scores.npy"]
    plot_output: !join [*output_path, "/scores.png"]
    record_path: !join [*output_path, "/VIDYA"]