env:
    env_name: &env_name "Pendulum-v1"
    record: True
    seed: 69420
    min_expected_reward: 0
    ## NEED TO PUT STATE INFO HERE
    discrete: False
    obs_dim: 3
    action_dim: 1

network:
    network_type: "normal"
    network_config:
        normal:
        cnn:
        lstm: 

model_training:
    num_episodes_eval: 5
    record_freq: 5
    summary_freq: 1
    use_baseline: &use_baseline True
    normalize_advantage: True
    device: "gpu" # cpu/gpu
    compile: False
    compile_mode: "default"
    batchTheBatch: 15

hyper_params: 
    max_ep_len: 200 # maximum episode length (Note: this value must be strictly less than or equal to our batch size)
    num_batches: 20000 # number of batches trained on
    batch_size: 2000 # number of steps used to compute each policy update
    learning_rate: 0.03
    gamma: 0.9 # the discount factor
    n_layers: 2
    layer_size: 64

output:
    output_path: &output_path !join ["ModelWeights/", *env_name, "-{}-"]
    actor_output: !join [*output_path, "/actor.weights.pt"]
    critic_output: !join [*output_path, "/critic.weights.pt"]
    log_path: !join [*output_path, "/log.txt"]
    scores_output: !join [*output_path, "/scores.npy"]
    plot_output: !join [*output_path, "/scores.png"]
    record_path: !join [*output_path, "/VIDYA"]