env:
    env_name: &env_name "LunarLander-v2"
    record: True
    seed: &seed 69420
    min_expected_reward: 300
    ## NEED TO PUT STATE INFO HERE
    discrete: True
    obs_dim: 8
    action_dim: 4

model_training:
    num_episodes_eval: 5
    record_freq: 5
    summary_freq: 1
    use_baseline: &use_baseline True
    normalize_advantage: False
    device: "gpu" # cpu/gpu
    compile: False
    compile_mode: "default"

hyper_params: 
    max_ep_len: 300 # maximum episode length (Note: this value must be strictly less than or equal to our batch size)
    num_batches: 1000 # number of batches trained on
    batch_size: 1000 # number of steps used to compute each policy update
    learning_rate: 0.001
    gamma: 0.99 # the discount factor
    n_layers: 4
    layer_size: 64

output:
    output_path: &output_path !join ["ModelWeights/", *env_name, "-{}-"]
    actor_output: !join [*output_path, "/actor.weights.pt"]
    critic_output: !join [*output_path, "/critic.weights.pt"]
    log_path: !join [*output_path, "/log.txt"]
    scores_output: !join [*output_path, "/scores.npy"]
    plot_output: !join [*output_path, "/scores.png"]
    record_path: !join [*output_path, "/VIDYA"]